//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import jakarta.xml.bind.annotation.*

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Activity"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["activity"])
@XmlRootElement(name = "Activities")
class Activities {
    /**
     * Gets the value of the activity property.
     *
     * @return
     * possible object is
     * [Activity]
     */
    /**
     * Sets the value of the activity property.
     *
     * @param value
     * allowed object is
     * [Activity]
     */
    @XmlElement(name = "Activity", required = true)
    var activity: Activity? = null
}