//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import jakarta.xml.bind.annotation.*
import javax.xml.datatype.XMLGregorianCalendar

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Id"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Lap" maxOccurs="unbounded"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Creator"/>
 * &lt;/sequence>
 * &lt;attribute name="Sport" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Running"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["id", "lap", "creator"])
@XmlRootElement(name = "Activity")
class Activity {
    /**
     * Gets the value of the id property.
     *
     * @return
     * possible object is
     * [XMLGregorianCalendar]
     */
    /**
     * Sets the value of the id property.
     *
     * @param value
     * allowed object is
     * [XMLGregorianCalendar]
     */
    @XmlElement(name = "Id", required = true)
    var id: XMLGregorianCalendar? = null

    @XmlElement(name = "Lap", required = true)
    protected var lap: List<Lap>? = null
    /**
     * Gets the value of the creator property.
     *
     * @return
     * possible object is
     * [Creator]
     */
    /**
     * Sets the value of the creator property.
     *
     * @param value
     * allowed object is
     * [Creator]
     */
    @XmlElement(name = "Creator", required = true)
    var creator: Creator? = null
    /**
     * Gets the value of the sport property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the sport property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "Sport", required = true)
    var sport: String? = null


}