//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import jakarta.xml.bind.annotation.XmlAccessType
import jakarta.xml.bind.annotation.XmlAccessorType
import jakarta.xml.bind.annotation.XmlElement
import jakarta.xml.bind.annotation.XmlRootElement
import jakarta.xml.bind.annotation.XmlType

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Name"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Build"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}LangID"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}PartNumber"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["name", "build", "langID", "partNumber"])
@XmlRootElement(name = "Author")
class Author {
    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Name", required = true)
    var name: String? = null
    /**
     * Gets the value of the build property.
     *
     * @return
     * possible object is
     * [Build]
     */
    /**
     * Sets the value of the build property.
     *
     * @param value
     * allowed object is
     * [Build]
     */
    @XmlElement(name = "Build", required = true)
    var build: Build? = null
    /**
     * Gets the value of the langID property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the langID property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LangID", required = true)
    var langID: String? = null
    /**
     * Gets the value of the partNumber property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the partNumber property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PartNumber", required = true)
    var partNumber: String? = null
}