//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import jakarta.xml.bind.annotation.XmlAccessType
import jakarta.xml.bind.annotation.XmlAccessorType
import jakarta.xml.bind.annotation.XmlElement
import jakarta.xml.bind.annotation.XmlRootElement
import jakarta.xml.bind.annotation.XmlType

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Name"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}UnitId"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}ProductID"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Version"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["name", "unitId", "productID", "version"])
@XmlRootElement(name = "Creator")
class Creator {
    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Name", required = true)
    var name: String? = null
    /**
     * Gets the value of the unitId property.
     *
     */
    /**
     * Sets the value of the unitId property.
     *
     */
    @XmlElement(name = "UnitId")
    var unitId: Long = 0
    /**
     * Gets the value of the productID property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the productID property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProductID", required = true)
    var productID: String? = null
    /**
     * Gets the value of the version property.
     *
     * @return
     * possible object is
     * [Version]
     */
    /**
     * Sets the value of the version property.
     *
     * @param value
     * allowed object is
     * [Version]
     */
    @XmlElement(name = "Version", required = true)
    var version: Version? = null
}