//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import io.shodo.tcxcorrector.model.extensions.LX
import io.shodo.tcxcorrector.model.extensions.TPX
import jakarta.xml.bind.annotation.XmlAccessType
import jakarta.xml.bind.annotation.XmlAccessorType
import jakarta.xml.bind.annotation.XmlElement
import jakarta.xml.bind.annotation.XmlRootElement
import jakarta.xml.bind.annotation.XmlType

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}LX"/>
 * &lt;/choice>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["tpx", "lx"])
@XmlRootElement(name = "Extensions")
class Extensions {
    @XmlElement(name = "TPX", namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2")
    var tpx: TPX? = null

    @XmlElement(name = "LX", namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2")
    var lx: LX? = null

}