//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.trainingdb

import jakarta.xml.bind.annotation.XmlAccessType
import jakarta.xml.bind.annotation.XmlAccessorType
import jakarta.xml.bind.annotation.XmlElement
import jakarta.xml.bind.annotation.XmlRootElement
import jakarta.xml.bind.annotation.XmlType

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}VersionMajor"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}VersionMinor"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}BuildMajor"/>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}BuildMinor"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["versionMajor", "versionMinor", "buildMajor", "buildMinor"])
@XmlRootElement(name = "Version")
class Version {
    /**
     * Gets the value of the versionMajor property.
     *
     */
    /**
     * Sets the value of the versionMajor property.
     *
     */
    @XmlElement(name = "VersionMajor")
    var versionMajor: Byte = 0
    /**
     * Gets the value of the versionMinor property.
     *
     */
    /**
     * Sets the value of the versionMinor property.
     *
     */
    @XmlElement(name = "VersionMinor")
    var versionMinor: Byte = 0
    /**
     * Gets the value of the buildMajor property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the buildMajor property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "BuildMajor", required = true)
    var buildMajor: String? = null
    /**
     * Gets the value of the buildMinor property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the buildMinor property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "BuildMinor", required = true)
    var buildMinor: String? = null
}