//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//
package io.shodo.tcxcorrector.model.extensions

import jakarta.xml.bind.annotation.*
import java.math.BigDecimal

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}AvgSpeed"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["avgSpeed","avgRunCadence","maxRunCadence"])
@XmlRootElement(name = "LX")
class LX {


    @XmlElement(name = "AvgSpeed", required = true)
    var avgSpeed: BigDecimal? = null

    @XmlElement(name = "AvgRunCadence", required = false)
    var avgRunCadence: Int? = null

    @XmlElement(name = "MaxRunCadence", required = false)
    var maxRunCadence: Int? = null
}