//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.shodo.tcxcorrector.model.extensions;
